# Generated by Django 5.0.6 on 2024-06-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('on_sale', models.BooleanField(default=False)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('review_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
