# Generated by Django 5.0.7 on 2024-08-05 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0002_payment_remove_product_on_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(help_text='Enter the botanical name', max_length=100)),
                ('family', models.CharField(help_text='Enter the family name', max_length=100)),
                ('origin', models.CharField(help_text='Enter the origin', max_length=100)),
                ('chromosome_number', models.CharField(help_text='Enter the chromosome number', max_length=20)),
                ('common_name', models.CharField(help_text='Enter the common name', max_length=100)),
                ('soil', models.CharField(help_text='Enter the soil type', max_length=100)),
                ('propagation', models.CharField(help_text='Enter the propagation method', max_length=100)),
                ('seed_germination_temperature', models.CharField(help_text='Enter the seed germination temperature range', max_length=50)),
                ('yield_info', models.CharField(help_text='Enter the yield information', max_length=100)),
                ('varieties', models.TextField(help_text='Enter the varieties, separated by commas')),
                ('pests_and_diseases', models.TextField(help_text='Enter the pests and diseases, separated by commas')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter your phone number', max_length=15)),
                ('country', models.CharField(help_text='Enter your country', max_length=50)),
                ('city', models.CharField(help_text='Enter your city', max_length=50)),
                ('subject', models.CharField(help_text='Enter the subject of your message', max_length=200)),
                ('message', models.TextField(help_text='Enter your message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale_price',
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
