# Generated by Django 5.0.6 on 2024-06-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
    ]
