# Generated by Django 5.0.6 on 2024-07-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0003_remove_userprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
