# Generated by Django 5.0.6 on 2024-07-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0003_remove_userprofile_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
