# Generated by Django 5.0.7 on 2024-07-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0009_articles'),
        ('GreenWebsite', '0009_order_orderitem'),
    ]

    operations = [
    ]
