# Generated by Django 5.0.7 on 2024-07-26 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0010_merge_0009_articles_0009_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(help_text='Enter the botanical name', max_length=100)),
                ('family', models.CharField(help_text='Enter the family name', max_length=100)),
                ('origin', models.CharField(help_text='Enter the origin', max_length=100)),
                ('chromosome_number', models.CharField(help_text='Enter the chromosome number', max_length=20)),
                ('common_name', models.CharField(help_text='Enter the common name', max_length=100)),
                ('soil', models.CharField(help_text='Enter the soil type', max_length=100)),
                ('propagation', models.CharField(help_text='Enter the propagation method', max_length=100)),
                ('seed_germination_temperature', models.CharField(help_text='Enter the seed germination temperature range', max_length=50)),
                ('yield_info', models.CharField(help_text='Enter the yield information', max_length=100)),
                ('varieties', models.TextField(help_text='Enter the varieties, separated by commas')),
                ('pests_and_diseases', models.TextField(help_text='Enter the pests and diseases, separated by commas')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product_img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'is_paid')},
        ),
        migrations.AddField(
            model_name='articles',
            name='botanical_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='GreenWebsite.botanicalentry'),
        ),
    ]
