# Generated by Django 5.0.7 on 2024-07-24 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0010_merge_0009_articles_0009_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product_img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_img/'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'is_paid')},
        ),
    ]
