# Generated by Django 5.0.7 on 2024-07-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0012_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='botanical_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='GreenWebsite.botanicalentry'),
        ),
    ]
