# Generated by Django 5.0.7 on 2024-07-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenWebsite', '0013_alter_articles_botanical_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter your phone number', max_length=15)),
                ('country', models.CharField(help_text='Enter your country', max_length=50)),
                ('city', models.CharField(help_text='Enter your city', max_length=50)),
                ('subject', models.CharField(help_text='Enter the subject of your message', max_length=200)),
                ('message', models.TextField(help_text='Enter your message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
